# Generated by Django 4.0.5 on 2022-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer Text'),
        ),
    ]
